# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iLetter' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iLetter
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'FBSDKCoreKit'  
pod 'FBSDKLoginKit'
pod 'GoogleSignIn'

end
